### ISSUE TITLE
Implement Google Analytic Event Tracking

### ISSUE THREAD

**Issue by x0xMaximus** [SuLab/mark2cure#225]
[Event Tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) can be used for detailed reporting on:

- [ ] Training progression
- [ ] Microtask entrance and departure
- [ ] FAQ, Search, and other reference usage
- [ ] New feature evaluation of usage

**Comment by x0xMaximus** [comment]
Tag Manager setup & Google Web Masters verified

**Comment by x0xMaximus** [comment]
There needs to be clarification of the role between the user (Mark Cure), the Page, and the Web App on Facebook.

**Comment by x0xMaximus** [comment]
Done integrating with TagManager. Handing off to @gtsueng to manage that account
